title       = "nhaccuatui"
baseURL     = "https://nhaccuatui-cli.tamnd.com/"
description = "A command line for nhaccuatui."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/nhaccuatui-cli"
